const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export {
  LOGIN_SUCCESS,
  GET_ALL_PRODUCT,
  GET_PRODUCT_DETAIL,
  ADD_PRODUCT_SUCCESS,
  UPDATE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_SUCCESS,
};