const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

const GET_ALL_CART = "GET_ALL_CART";
const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";

export {
  LOGIN_SUCCESS,
  GET_ALL_PRODUCT,
  GET_PRODUCT_DETAIL,
  ADD_PRODUCT_SUCCESS,
  UPDATE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_SUCCESS,
  GET_ALL_CART,
  ADD_CART_SUCCESS,
  UPDATE_CART_SUCCESS,
  DELETE_CART_SUCCESS,
};