const BACKGROUND_COLOR_LOCK = "#9c27b0";

const ADD_TYPE = "ADD_TYPE";
const UPDATE_TYPE = "UPDATE_TYPE";
const DELETE_TYPE = "DELETE_TYPE";
const VIEW_TYPE = "VIEW_TYPE";

export { BACKGROUND_COLOR_LOCK, ADD_TYPE, DELETE_TYPE, VIEW_TYPE, UPDATE_TYPE };